"""add selected modules to reports

Revision ID: 1e83fb794671
Revises: 0b141bcdeb17
Create Date: 2026-08-28 14:20:30.835919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e83fb794671'
down_revision: Union[str, Sequence[str], None] = '0b141bcdeb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('selected_modules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'selected_modules')
    # ### end Alembic commands ###
