"""add bank account to budgets and savings

Revision ID: 3cfdfb5b32d5
Revises: 753ccd7808f2
Create Date: 2026-08-26 19:51:31.502179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cfdfb5b32d5'
down_revision: Union[str, Sequence[str], None] = '753ccd7808f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_accounts', 'account_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'Savings'::character varying"))
    op.alter_column('bank_accounts', 'current_balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bank_accounts', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('unique_user_bank'), 'bank_accounts', type_='unique')
    op.drop_index(op.f('uq_bank_accounts_user_bank'), table_name='bank_accounts')
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.drop_constraint(op.f('bank_accounts_user_id_fkey'), 'bank_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'bank_accounts', 'users', ['user_id'], ['id'])
    op.drop_column('bank_accounts', 'created_at')
    op.add_column('budgets', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.alter_column('budgets', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('budgets', 'monthly_limit',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('budgets', 'month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('budgets', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.drop_constraint(op.f('budgets_user_id_fkey'), 'budgets', type_='foreignkey')
    op.create_foreign_key(None, 'budgets', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'])
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.drop_constraint(op.f('expenses_user_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'users', ['user_id'], ['id'])
    op.alter_column('income', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_income_id'), 'income', ['id'], unique=False)
    op.drop_constraint(op.f('income_user_id_fkey'), 'income', type_='foreignkey')
    op.create_foreign_key(None, 'income', 'users', ['user_id'], ['id'])
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.drop_constraint(op.f('reports_user_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'])
    op.add_column('savings_goals', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.alter_column('savings_goals', 'target_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('savings_goals', 'current_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_savings_goals_id'), 'savings_goals', ['id'], unique=False)
    op.drop_constraint(op.f('savings_goals_user_id_fkey'), 'savings_goals', type_='foreignkey')
    op.create_foreign_key(None, 'savings_goals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'savings_goals', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')
    op.add_column('savings_transactions', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('savings_transactions_goal_id_fkey'), 'savings_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'savings_transactions', 'savings_goals', ['goal_id'], ['id'])
    op.create_foreign_key(None, 'savings_transactions', 'bank_accounts', ['bank_account_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'savings_transactions', type_='foreignkey')
    op.drop_constraint(None, 'savings_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('savings_transactions_goal_id_fkey'), 'savings_transactions', 'savings_goals', ['goal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('savings_transactions', 'bank_account_id')
    op.drop_constraint(None, 'savings_goals', type_='foreignkey')
    op.drop_constraint(None, 'savings_goals', type_='foreignkey')
    op.create_foreign_key(op.f('savings_goals_user_id_fkey'), 'savings_goals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_savings_goals_id'), table_name='savings_goals')
    op.alter_column('savings_goals', 'current_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('savings_goals', 'target_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('savings_goals', 'bank_account_id')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_user_id_fkey'), 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.create_foreign_key(op.f('income_user_id_fkey'), 'income', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_income_id'), table_name='income')
    op.alter_column('income', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_user_id_fkey'), 'expenses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.alter_column('expenses', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('expenses', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.create_foreign_key(op.f('budgets_user_id_fkey'), 'budgets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.alter_column('budgets', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('budgets', 'month',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('budgets', 'monthly_limit',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('budgets', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('budgets', 'bank_account_id')
    op.add_column('bank_accounts', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bank_accounts', type_='foreignkey')
    op.create_foreign_key(op.f('bank_accounts_user_id_fkey'), 'bank_accounts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.create_index(op.f('uq_bank_accounts_user_bank'), 'bank_accounts', ['user_id', sa.literal_column('lower(TRIM(BOTH FROM bank_name))')], unique=True)
    op.create_unique_constraint(op.f('unique_user_bank'), 'bank_accounts', ['user_id', 'bank_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('bank_accounts', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('bank_accounts', 'current_balance',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('bank_accounts', 'account_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Savings'::character varying"))
    # ### end Alembic commands ###
